package com.example.dao;

import com.example.dataobject.UserPsw;

public interface UserPswMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Feb 16 21:26:28 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Feb 16 21:26:28 GMT+08:00 2020
     */
    int insert(UserPsw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Feb 16 21:26:28 GMT+08:00 2020
     */
    int insertSelective(UserPsw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Feb 16 21:26:28 GMT+08:00 2020
     */
    UserPsw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Feb 16 21:26:28 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(UserPsw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Feb 16 21:26:28 GMT+08:00 2020
     */
    int updateByPrimaryKey(UserPsw record);
}